#install packages needed 
install.packages("devtools")
install_github("ajparsons/everypoliticianR")
install.packages("remotes")
remotes::install_github("jblumenau/twfyR")
install.github("lxml")
install.packages('XML')
install.packages("lubridate")
install.packages("XLConnect")
install.packages("rlist")
install.packages("sqldf")
install.packages("gmodels")
install.packages("ggthemes")
install.packages("widyr")
install.packages("igraph")
install.packages("ggraph")
install.packages("lda")
install.packages("LDAvis")
install.packages("servr")
#load library
library(devtools)
library(everypoliticianR)
library(twfyR)
