#install packages needed 
install.packages("devtools")
install_github("ajparsons/everypoliticianR")
install.packages("remotes")
remotes::install_github("jblumenau/twfyR")
install.github("lxml")
install.packages('XML')
install.packages("lubridate")
install.packages("XLConnect")
install.packages("rlist")
install.packages("sqldf")
install.packages("gmodels")
install.packages("ggthemes")
install.packages("widyr")
install.packages("igraph")
install.packages("ggraph")
install.packages("lda")
install.packages("LDAvis")
install.packages("servr")
install.packages("textstem")
install.packages("stringi")
install.packages("sentimentR")
install.packages("ldatuning")
install.packages("topicmodels")
install.packages("NMF")
install.packages("Biobase")

